version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    depends_on: []
    image: brainpiano_frontend_dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/src
      - /home/maarten/projects/aspiration/src:/npm/aspiration
      - /home/maarten/projects/react-form-state-context/src:/npm/react-form-state-context
      - /home/maarten/projects/react-default-props-context/src:/npm/react-default-props-context
      - /home/maarten/projects/skandha/src:/npm/skandha
      - /home/maarten/projects/skandha-facets/src:/npm/skandha-facets
      - /home/maarten/projects/skandha-mobx/src:/npm/skandha-mobx
