import {
  root,
  fifth,
  flat3,
  flat5,
  flat6,
  flat7,
  flat9,
  fourth,
  ninth,
  seventh,
  sharp5,
  sixth,
  third,
  thirteenth,
  flat13,
} from 'src/keyboard/note_constants';

export const voicings = {
  minor: {
    'Min6+9': [ninth, flat3, fifth, thirteenth],
    'Min7+9': [ninth, flat3, fifth, flat7],
    'Min7b5+9': [ninth, flat3, flat5, flat7],
    'MinMaj+9': [ninth, flat3, fifth, seventh],
    Min6: [flat3, fifth, thirteenth],
    Min7: [flat3, fifth, flat7],
    Min7b5: [flat3, flat5, flat7],
    Min: [flat3, fifth],
    MinMaj: [flat3, fifth, seventh],
  },
  major: {
    'Maj6+9': [ninth, third, sixth],
    'Maj7+9': [ninth, third, fifth, seventh],
    Maj6: [third, sixth],
    Maj7: [third, fifth, seventh],
    Maj: [third, fifth],
  },
  dominant: {
    '7+13': [third, fifth, thirteenth, flat7],
    '7+9': [ninth, third, fifth, flat7],
    '7+b13': [third, fifth, flat13, flat7],
    '7+b5': [third, flat5, flat7],
    '7+b5+b13': [third, flat5, flat13, flat7],
    '7+b9': [flat9, third, fifth, flat7],
    '7+b9+13': [flat9, third, fifth, thirteenth, flat7],
    '7+b9+b13': [flat9, third, fifth, flat13, flat7],
    '7': [third, fifth, flat7],
  },
  skip: {
    SoWhat: [root, fourth, flat7, flat3, fifth],
    Aug: [root, third, sharp5],
    Dim: [flat3, flat5, thirteenth],
  },
  scales: {
    Chromatic: [
      root,
      flat9,
      ninth,
      flat3,
      third,
      fourth,
      flat5,
      fifth,
      flat6,
      sixth,
      flat7,
      seventh,
    ],
  },
};
